### ISSUE TITLE
Evaluating existing pertubations

### ISSUE THREAD

**Issue by shashankskagnihotri** [cv-stuttgart/PCFA#1]
Dear authors, 
This is a nice paper with a good idea. I'm currently trying to reproduce the results reported by the paper. 
For evaluating existing perturbations, especially universal perturbations the process is time taking. 
Is it possible for the authors to also make the files for the "--perturbation_sourcefolder" generated by the authors for different scenarios publicly available as it will help with reproducibility?

Regards
Shashank Agnihotri

**Comment by slenderlori** [comment]
Thanks, that is a good point. I try to make the files available within the next week.

**Comment by shashankskagnihotri** [comment]
Great, thanks a lot. :D

**Comment by slenderlori** [comment]
I just added the perturbation files under universal_perturbations. You can just pass the .npy files as --perturbation_sourcefolder, the loader will recognize that it is a file and only use the file. As an example, to test the universal SpyNet perturbation on Kitti15 for FlowNet2, you can execute:

python3 evaluate_PCFA.py --net=FlowNet2 --dataset=Kitti15 --dataset_stage=evaluation --origin_net=SpyNet --perturbation_sourcefolder=universal_perturbations/SpyNet_Kitti15.npy --joint_perturbation --universal_perturbation

It is only important that the --origin_net and the --dataset match the specified perturbation. I also added more details to the readme under "Evaluating the Provided Universal Perturbations".

Hope that helps!

**Comment by shashankskagnihotri** [comment]
That is very helpful, thanks a lot. :D
